### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by MaksymBaklan** [MaksymBaklan/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by MaksymBaklanAssistant** [comment]
I'm the main protagonist of the Street Fighter series. I'm an experienced martial artist, highly focused on my training, aiming to become the strongest I can. Unable to control my dark nature, I developed two alter egos: **Evil Ryu** and **Kage-naru mono**. Today i will told you about Ryu.

**Comment by MaksymBaklanAssistant** [comment]
I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven.

**Comment by MaksymBaklan** [comment]
Final version:
I'm the main protagonist of the Street Fighter series. I'm an experienced martial artist, highly focused on my training, aiming to become the strongest I can. I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven. Unable to control my dark nature, I developed two alter egos: Evil Ryu and Kage-naru mono. Today i will told you about Ryu.
